name = "Hashing"
uuid = "59f36028-7e5a-47c1-b5da-23e00bab95ae"
authors = ["Erich Neun <erich-9@gmx.de> and contributors"]
version = "0.0.1"

[deps]
Libgcrypt_jll = "d4300ac3-e22c-5743-9152-c294e39db1e4"
OpenSSL_jll = "458c3c95-2e84-50aa-8efc-19380b2a3a95"

[compat]
Aqua = "0.8"
Libgcrypt_jll = "1.8"
Nettle = "1"
OpenSSL_jll = "3"
Test = "<0.0.1, 1"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Nettle = "49dea1ee-f6fa-5aa6-9a11-8816cee7d4b9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Nettle", "Test"]
